apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: tic-tac-toe-deployment
spec:
  replicas: 1
  selector:
    app: tic-tac-toe
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      initContainers:
        - name: set-changed
          image: alpine:latest
          command: ['sh', '-c', 'echo "::set-output name=changed::true"']
      containers:
        - name: tic-tac-toe-container
          image: tic-tac-toe-imagestream:latest
          ports:
            - containerPort: 5000

