apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: tic-tac-toe
spec:
  replicas: 1
  selector:
    app: tic-tac-toe
    deploymentconfig: tic-tac-toe
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: tic-tac-toe
        deploymentconfig: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe
          image: jleir0/tic-tac-toe:latest

