apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspacec35d79b1c931470f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe
          image: jleir0/tic-tac-toe:latest
