name: CI/CD Pipeline

on:
  push:
    tags:
      - '*' 

env:
  PROJECT_NAME: tic-tac-toe
  
jobs:
  ci_feature:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Get Tag Name
      id: tag
      run: |
        echo "::set-output name=tag::$(git describe --tags --abbrev=0)"      
        
    - name: Build Container Image
      run: |
        TAG_NAME="${{ steps.tag.outputs.tag }}"
        docker build -t ${{ env.PROJECT_NAME }}:$TAG_NAME .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_PAT }}
        docker push jleir0/${{ env.PROJECT_NAME }}:$TAG_NAME

    - name: Cleanup Docker Credentials
      run: docker logout
      
    - name: Run Automated Tests
      run: |
        # TODO
        
  cd_feature:
    runs-on: ubuntu-latest
    needs: ci_feature
    
    steps:
    - name: Deploy
      if: success() && github.ref == 'refs/heads/main'
      run: |
        # TODO

    - name: Notify on Failure
      if: failure()
      run: |
        # TODO
